[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gcc", "gnumake"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["VITE_BASE_PATH=root npm run build"]

[start]
cmd = "node dist/server/index.js"
